# Generated by Django 3.0.3 on 2020-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardno', models.CharField(max_length=100)),
                ('cvvno', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('housetype', models.CharField(max_length=100)),
                ('myfile', models.ImageField(upload_to='pictures')),
            ],
            options={
                'db_table': 'myfiles',
            },
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=20)),
                ('pathh', models.FileField(upload_to='pictures')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=26)),
                ('addres', models.CharField(max_length=60)),
                ('occupation', models.CharField(max_length=40)),
                ('workingarea', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UploadrentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures')),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('housetype', models.CharField(max_length=100)),
            ],
        ),
    ]
